
# This file is automatically generated, you probably don't want to edit this

l2sttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "l2sttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            nul = 0,
            alt = 0,
            lint = 2,
            welch = TRUE,
            dtab = FALSE,
            plt = FALSE,
            pll = FALSE, ...) {

            super$initialize(
                package="Likelihood",
                name="l2sttest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..nul <- jmvcore::OptionNumber$new(
                "nul",
                nul,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=10,
                default=2)
            private$..welch <- jmvcore::OptionBool$new(
                "welch",
                welch,
                default=TRUE)
            private$..dtab <- jmvcore::OptionBool$new(
                "dtab",
                dtab,
                default=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..nul)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..welch)
            self$.addOption(private$..dtab)
            self$.addOption(private$..plt)
            self$.addOption(private$..pll)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        nul = function() private$..nul$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        welch = function() private$..welch$value,
        dtab = function() private$..dtab$value,
        plt = function() private$..plt$value,
        pll = function() private$..pll$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..nul = NA,
        ..alt = NA,
        ..lint = NA,
        ..welch = NA,
        ..dtab = NA,
        ..plt = NA,
        ..pll = NA)
)

l2sttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "l2sttestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        l2sttest = function() private$.items[["l2sttest"]],
        l2sttest2 = function() private$.items[["l2sttest2"]],
        l2sttestd = function() private$.items[["l2sttestd"]],
        plot = function() private$.items[["plot"]],
        plotc = function() private$.items[["plotc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LR Independent Samples t-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="l2sttest",
                title="Support",
                rows=3,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"),
                    list(
                        `name`="mdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="sed", 
                        `title`="SE difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="l2sttest2",
                title="Support Interval for mean difference",
                rows=1,
                columns=list(
                    list(
                        `name`="mdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="l2sttestd",
                title="Group Descriptives",
                visible=FALSE,
                rows=2,
                columns=list(
                    list(
                        `name`="gp", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="number"),
                    list(
                        `name`="Mean", 
                        `type`="number"),
                    list(
                        `name`="Median", 
                        `type`="number"),
                    list(
                        `name`="SD", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="`Means with S-{lint} support intervals`",
                width=400,
                height=300,
                renderFun=".plot",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood function with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                visible=FALSE))}))

l2sttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "l2sttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Likelihood",
                name = "l2sttest",
                version = c(1,0,0),
                options = options,
                results = l2sttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' LR Independent Samples t-Test
#'
#' Independent samples analysis where null and alternative hypotheses can be 
#' specified.
#' 
#' @param data .
#' @param dep a (non-empty) numeric vector of data values
#' @param group an integer vector the same length as data, coding for 2 groups
#' @param nul value for the null hypothesis, default = 0
#' @param alt value for an alternative hypothesis, default = 0
#' @param lint likelihood interval given as support values, e.g. 2 or 3,
#'   default = 2
#' @param welch perform Welch's t-test, \code{TRUE} (default) or \code{FALSE}
#' @param dtab .
#' @param plt .
#' @param pll .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$l2sttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$l2sttest2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$l2sttestd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$l2sttest$asDF}
#'
#' \code{as.data.frame(results$l2sttest)}
#'
#' @export
l2sttest <- function(
    data,
    dep,
    group,
    nul = 0,
    alt = 0,
    lint = 2,
    welch = TRUE,
    dtab = FALSE,
    plt = FALSE,
    pll = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("l2sttest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- l2sttestOptions$new(
        dep = dep,
        group = group,
        nul = nul,
        alt = alt,
        lint = lint,
        welch = welch,
        dtab = dtab,
        plt = plt,
        pll = pll)

    analysis <- l2sttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

