
# This file is automatically generated, you probably don't want to edit this

laov1wOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "laov1wOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            group = NULL,
            con1 = NULL,
            con2 = NULL,
            desc = FALSE,
            descPlot = FALSE,
            norm = FALSE,
            qq = FALSE,
            eqv = FALSE, ...) {

            super$initialize(
                package="Likelihood",
                name="laov1w",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariable$new(
                "deps",
                deps,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=TRUE,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..con1 <- jmvcore::OptionVariable$new(
                "con1",
                con1,
                required=FALSE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..con2 <- jmvcore::OptionVariable$new(
                "con2",
                con2,
                required=FALSE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..descPlot <- jmvcore::OptionBool$new(
                "descPlot",
                descPlot,
                default=FALSE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=FALSE)
            private$..qq <- jmvcore::OptionBool$new(
                "qq",
                qq,
                default=FALSE)
            private$..eqv <- jmvcore::OptionBool$new(
                "eqv",
                eqv,
                default=FALSE)

            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..con1)
            self$.addOption(private$..con2)
            self$.addOption(private$..desc)
            self$.addOption(private$..descPlot)
            self$.addOption(private$..norm)
            self$.addOption(private$..qq)
            self$.addOption(private$..eqv)
        }),
    active = list(
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        con1 = function() private$..con1$value,
        con2 = function() private$..con2$value,
        desc = function() private$..desc$value,
        descPlot = function() private$..descPlot$value,
        norm = function() private$..norm$value,
        qq = function() private$..qq$value,
        eqv = function() private$..eqv$value),
    private = list(
        ..deps = NA,
        ..group = NA,
        ..con1 = NA,
        ..con2 = NA,
        ..desc = NA,
        ..descPlot = NA,
        ..norm = NA,
        ..qq = NA,
        ..eqv = NA)
)

laov1wResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "laov1wResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        anova = function() private$.items[["anova"]],
        desc = function() private$.items[["desc"]],
        assump = function() private$.items[["assump"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LR One-Way ANOVA")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="One-Way ANOVA",
                rows=5,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Model Comparisons", 
                        `type`="text"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="Sc", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="text"),
                    list(
                        `name`="F", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "GloverDixon")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Group Descriptives",
                rows=0,
                visible="(desc)",
                clearWith=list(
                    "group",
                    "miss"),
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    norm = function() private$.items[["norm"]],
                    eqv = function() private$.items[["eqv"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="assump",
                            title="Assumption Checks")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="norm",
                            title="Normality Test (Shapiro-Wilk)",
                            visible="(norm)",
                            rows="(deps)",
                            clearWith=list(
                                "miss",
                                "group"),
                            notes=list(
                                `p`="A low p-value suggests a violation of the assumption of normality"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `content`="($key)", 
                                    `type`="text"),
                                list(
                                    `name`="w", 
                                    `title`="W", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eqv",
                            title="Homogeneity of Variances Test (Levene's)",
                            refs=list(
                                "car",
                                "EdwardsF"),
                            visible="(eqv)",
                            rows="(deps)",
                            columns=list(
                                list(
                                    `name`="dep", 
                                    `title`="", 
                                    `content`="($key)", 
                                    `type`="text"),
                                list(
                                    `name`="S", 
                                    `type`="number"),
                                list(
                                    `name`="F", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `type`="text"),
                                list(
                                    `name`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(deps)",
                clearWith=list(
                    "group",
                    "miss"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        desc = function() private$.items[["desc"]],
                        qq = function() private$.items[["qq"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="desc",
                                height=350,
                                visible="(descPlot)",
                                renderFun=".desc",
                                clearWith=list()))
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="qq",
                                width=350,
                                height=300,
                                requiresData=TRUE,
                                visible="(qq)",
                                renderFun=".qq",
                                clearWith=list()))}))$new(options=options)))}))

laov1wBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "laov1wBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Likelihood",
                name = "laov1w",
                version = c(1,0,0),
                options = options,
                results = laov1wResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' One-Way ANOVA
#'
#' The Analysis of Variance (ANOVA) is used to explore the relationship
#' between a continuous dependent variable, and one or more categorical
#' explanatory variables. This 'One-Way ANOVA' is a simplified version of
#' the 'normal' ANOVA, allowing only a single explanatory factor and.
#' dependent variables. Contrasts can be specified whose weights should sum
#' to zero, but do not need to be orthogonal to each other. Support values, 
#' S, represent log likelihood ratio. They are given for each model 
#' comparison. Sc represent Akaike corrected values according to the 
#' number of parameters
#' 
#' @param data the data as a data frame
#' @param deps a string naming the dependent variables in \code{data}
#' @param group a string naming the grouping or independent variable in
#'   \code{data}
#' @param con1 .
#' @param con2 .
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param descPlot \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   plots
#' @param norm \code{TRUE} or \code{FALSE} (default), perform Shapiro-Wilk
#'   test of normality
#' @param qq \code{TRUE} or \code{FALSE} (default), provide a Q-Q plot of
#'   residuals
#' @param eqv \code{TRUE} or \code{FALSE} (default), perform Levene's test for
#'   homogeneity of variances
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a table of the test results \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table containing the group descriptives \cr
#'   \code{results$assump$norm} \tab \tab \tab \tab \tab a table containing the normality tests \cr
#'   \code{results$assump$eqv} \tab \tab \tab \tab \tab a table of homogeneity of variances tests \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of groups of plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anova$asDF}
#'
#' \code{as.data.frame(results$anova)}
#'
#' @export
laov1w <- function(
    data,
    deps,
    group,
    con1,
    con2,
    desc = FALSE,
    descPlot = FALSE,
    norm = FALSE,
    qq = FALSE,
    eqv = FALSE,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("laov1w requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(deps))
            deps <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                required=TRUE)
        if (missing(group))
            group <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs")
    }

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(con1)) con1 <- jmvcore::resolveQuo(jmvcore::enquo(con1))
    if ( ! missing(con2)) con2 <- jmvcore::resolveQuo(jmvcore::enquo(con2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(con1), con1, NULL),
            `if`( ! missing(con2), con2, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- laov1wOptions$new(
        deps = deps,
        group = group,
        con1 = con1,
        con2 = con2,
        desc = desc,
        descPlot = descPlot,
        norm = norm,
        qq = qq,
        eqv = eqv)

    analysis <- laov1wClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

