
# This file is automatically generated, you probably don't want to edit this

LcorrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LcorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            depa = NULL,
            depb = NULL,
            alt = 0,
            lint = 2,
            ciWidth = 95,
            pll = FALSE,
            plt = FALSE,
            line = "none",
            se = FALSE, ...) {

            super$initialize(
                package="Likelihood",
                name="Lcorr",
                requiresData=TRUE,
                ...)

            private$..depa <- jmvcore::OptionVariable$new(
                "depa",
                depa,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..depb <- jmvcore::OptionVariable$new(
                "depb",
                depb,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=-1,
                max=1,
                default=0)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.99,
                default=95)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..line <- jmvcore::OptionList$new(
                "line",
                line,
                options=list(
                    "none",
                    "linear",
                    "smooth"),
                default="none")
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=FALSE)

            self$.addOption(private$..depa)
            self$.addOption(private$..depb)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..pll)
            self$.addOption(private$..plt)
            self$.addOption(private$..line)
            self$.addOption(private$..se)
        }),
    active = list(
        depa = function() private$..depa$value,
        depb = function() private$..depb$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        ciWidth = function() private$..ciWidth$value,
        pll = function() private$..pll$value,
        plt = function() private$..plt$value,
        line = function() private$..line$value,
        se = function() private$..se$value),
    private = list(
        ..depa = NA,
        ..depb = NA,
        ..alt = NA,
        ..lint = NA,
        ..ciWidth = NA,
        ..pll = NA,
        ..plt = NA,
        ..line = NA,
        ..se = NA)
)

LcorrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LcorrResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lcor = function() private$.items[["lcor"]],
        lcor1 = function() private$.items[["lcor1"]],
        plotc = function() private$.items[["plotc"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LR Correlation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lcor",
                title="Correlation",
                rows=3,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"),
                    list(
                        `name`="rdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lcor1",
                title="Intervals",
                rows=2,
                refs=list(
                    "Aitkin"),
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood function with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Scatterplot",
                width=500,
                height=450,
                renderFun=".plot",
                visible=FALSE))}))

LcorrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LcorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Likelihood",
                name = "Lcorr",
                version = c(1,0,0),
                options = options,
                results = LcorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' LR Correlation
#'
#' Bivariate correlation analysis where an alternative hypothesis correlation 
#' can be specified.
#' 
#' @param data .
#' @param depa .
#' @param depb .
#' @param alt .
#' @param lint .
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param pll .
#' @param plt .
#' @param line \code{none} (default), \code{linear}, or \code{smooth}, provide
#'   respectively no regression line,  a linear regression line, or a smoothed
#'   regression line
#' @param se \code{TRUE} or \code{FALSE} (default), show the standard error
#'   for the regression line
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lcor} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lcor1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lcor$asDF}
#'
#' \code{as.data.frame(results$lcor)}
#'
#' @export
Lcorr <- function(
    data,
    depa,
    depb,
    alt = 0,
    lint = 2,
    ciWidth = 95,
    pll = FALSE,
    plt = FALSE,
    line = "none",
    se = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Lcorr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(depa)) depa <- jmvcore::resolveQuo(jmvcore::enquo(depa))
    if ( ! missing(depb)) depb <- jmvcore::resolveQuo(jmvcore::enquo(depb))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(depa), depa, NULL),
            `if`( ! missing(depb), depb, NULL))


    options <- LcorrOptions$new(
        depa = depa,
        depb = depb,
        alt = alt,
        lint = lint,
        ciWidth = ciWidth,
        pll = pll,
        plt = plt,
        line = line,
        se = se)

    analysis <- LcorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

