
# This file is automatically generated, you probably don't want to edit this

LregOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LregOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            pred = NULL,
            plt = FALSE,
            lin = TRUE,
            quad = FALSE,
            cub = FALSE,
            quart = FALSE,
            lint = 2, ...) {

            super$initialize(
                package="Likelihood",
                name="Lreg",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..lin <- jmvcore::OptionBool$new(
                "lin",
                lin,
                default=TRUE)
            private$..quad <- jmvcore::OptionBool$new(
                "quad",
                quad,
                default=FALSE)
            private$..cub <- jmvcore::OptionBool$new(
                "cub",
                cub,
                default=FALSE)
            private$..quart <- jmvcore::OptionBool$new(
                "quart",
                quart,
                default=FALSE)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)

            self$.addOption(private$..dep)
            self$.addOption(private$..pred)
            self$.addOption(private$..plt)
            self$.addOption(private$..lin)
            self$.addOption(private$..quad)
            self$.addOption(private$..cub)
            self$.addOption(private$..quart)
            self$.addOption(private$..lint)
        }),
    active = list(
        dep = function() private$..dep$value,
        pred = function() private$..pred$value,
        plt = function() private$..plt$value,
        lin = function() private$..lin$value,
        quad = function() private$..quad$value,
        cub = function() private$..cub$value,
        quart = function() private$..quart$value,
        lint = function() private$..lint$value),
    private = list(
        ..dep = NA,
        ..pred = NA,
        ..plt = NA,
        ..lin = NA,
        ..quad = NA,
        ..cub = NA,
        ..quart = NA,
        ..lint = NA)
)

LregResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LregResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lreg = function() private$.items[["lreg"]],
        coef = function() private$.items[["coef"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LR Regression")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lreg",
                title="Polynomial Regression",
                rows=4,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Model Comparisons", 
                        `type`="text"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="Sc", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="`Model Coefficients - ${ dep }`",
                clearWith=list(
                    "dep",
                    "lint"),
                rows=5,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Scatterplot with Model fits",
                width=500,
                height=450,
                renderFun=".plot",
                visible=FALSE))}))

LregBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LregBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Likelihood",
                name = "Lreg",
                version = c(1,0,0),
                options = options,
                results = LregResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' LR Polynomial Regression
#'
#' Polynomial regression of two variables where different orders can be 
#' compared.
#' 
#' @param data .
#' @param dep .
#' @param pred .
#' @param plt .
#' @param lin .
#' @param quad .
#' @param cub .
#' @param quart .
#' @param lint a number between 1 and 100 (default: 2) specifying the
#'   likelihood support interval width
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lreg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table of model coefficients \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lreg$asDF}
#'
#' \code{as.data.frame(results$lreg)}
#'
#' @export
Lreg <- function(
    data,
    dep,
    pred,
    plt = FALSE,
    lin = TRUE,
    quad = FALSE,
    cub = FALSE,
    quart = FALSE,
    lint = 2) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Lreg requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(pred)) pred <- jmvcore::resolveQuo(jmvcore::enquo(pred))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(pred), pred, NULL))


    options <- LregOptions$new(
        dep = dep,
        pred = pred,
        plt = plt,
        lin = lin,
        quad = quad,
        cub = cub,
        quart = quart,
        lint = lint)

    analysis <- LregClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

