
# This file is automatically generated, you probably don't want to edit this

lttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            nul = 0,
            alt = 0,
            lint = 2,
            dtab = FALSE,
            plt = FALSE,
            pll = FALSE, ...) {

            super$initialize(
                package="Likelihood",
                name="lttest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..nul <- jmvcore::OptionNumber$new(
                "nul",
                nul,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=10,
                default=2)
            private$..dtab <- jmvcore::OptionBool$new(
                "dtab",
                dtab,
                default=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..nul)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..dtab)
            self$.addOption(private$..plt)
            self$.addOption(private$..pll)
        }),
    active = list(
        dep = function() private$..dep$value,
        nul = function() private$..nul$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        dtab = function() private$..dtab$value,
        plt = function() private$..plt$value,
        pll = function() private$..pll$value),
    private = list(
        ..dep = NA,
        ..nul = NA,
        ..alt = NA,
        ..lint = NA,
        ..dtab = NA,
        ..plt = NA,
        ..pll = NA)
)

lttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lttestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lttest = function() private$.items[["lttest"]],
        lttest2 = function() private$.items[["lttest2"]],
        lttestd = function() private$.items[["lttestd"]],
        plot = function() private$.items[["plot"]],
        plotc = function() private$.items[["plotc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="LR One Sample t-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lttest",
                title="Support",
                rows=3,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"),
                    list(
                        `name`="mdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lttest2",
                title="Support Interval for mean",
                rows=1,
                columns=list(
                    list(
                        `name`="Mean", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lttestd",
                title="Group Descriptives",
                visible=FALSE,
                rows=1,
                columns=list(
                    list(
                        `name`="gp", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="number"),
                    list(
                        `name`="Mean", 
                        `type`="number"),
                    list(
                        `name`="Median", 
                        `type`="number"),
                    list(
                        `name`="SD", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="`Mean with S-{lint} support interval`",
                width=400,
                height=300,
                renderFun=".plot",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood function with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                visible=FALSE))}))

lttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Likelihood",
                name = "lttest",
                version = c(1,0,0),
                options = options,
                results = lttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' LR One Sample t-Test
#'
#' One sample analysis where null and alternative hypotheses can be specified.
#' 
#' @param data .
#' @param dep .
#' @param nul .
#' @param alt .
#' @param lint .
#' @param dtab .
#' @param plt .
#' @param pll .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lttest2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lttestd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lttest$asDF}
#'
#' \code{as.data.frame(results$lttest)}
#'
#' @export
lttest <- function(
    data,
    dep,
    nul = 0,
    alt = 0,
    lint = 2,
    dtab = FALSE,
    plt = FALSE,
    pll = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lttest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- lttestOptions$new(
        dep = dep,
        nul = nul,
        alt = alt,
        lint = lint,
        dtab = dtab,
        plt = plt,
        pll = pll)

    analysis <- lttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

