
# This file is automatically generated, you probably don't want to edit this

propOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "propOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            counts = NULL,
            expected = FALSE,
            bi = FALSE,
            ciWidth = 95,
            lint = 2,
            pll = FALSE,
            ratio = NULL,
            varA = FALSE, ...) {

            super$initialize(
                package="Likelihood",
                name="prop",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                default=NULL,
                permitted=list(
                    "numeric"))
            private$..expected <- jmvcore::OptionBool$new(
                "expected",
                expected,
                default=FALSE)
            private$..bi <- jmvcore::OptionBool$new(
                "bi",
                bi,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=10,
                default=2)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..ratio <- jmvcore::OptionArray$new(
                "ratio",
                ratio,
                template=jmvcore::OptionNumber$new(
                    "ratio",
                    NULL,
                    min=0,
                    default=1),
                default=NULL)
            private$..varA <- jmvcore::OptionBool$new(
                "varA",
                varA,
                default=FALSE)

            self$.addOption(private$..var)
            self$.addOption(private$..counts)
            self$.addOption(private$..expected)
            self$.addOption(private$..bi)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..lint)
            self$.addOption(private$..pll)
            self$.addOption(private$..ratio)
            self$.addOption(private$..varA)
        }),
    active = list(
        var = function() private$..var$value,
        counts = function() private$..counts$value,
        expected = function() private$..expected$value,
        bi = function() private$..bi$value,
        ciWidth = function() private$..ciWidth$value,
        lint = function() private$..lint$value,
        pll = function() private$..pll$value,
        ratio = function() private$..ratio$value,
        varA = function() private$..varA$value),
    private = list(
        ..var = NA,
        ..counts = NA,
        ..expected = NA,
        ..bi = NA,
        ..ciWidth = NA,
        ..lint = NA,
        ..pll = NA,
        ..ratio = NA,
        ..varA = NA)
)

propResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "propResults",
    inherit = jmvcore::Group,
    active = list(
        props = function() private$.items[["props"]],
        text = function() private$.items[["text"]],
        tests = function() private$.items[["tests"]],
        ctt2 = function() private$.items[["ctt2"]],
        ctt3 = function() private$.items[["ctt3"]],
        plotc = function() private$.items[["plotc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Way Categorical Data")
            self$add(jmvcore::Table$new(
                options=options,
                name="props",
                title="`Proportions - ${var}`",
                rows="(levels(var))",
                clearWith=list(
                    "var",
                    "ratio",
                    "counts"),
                columns=list(
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="name[obs]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Observed", 
                        `visible`="(expected)"),
                    list(
                        `name`="count[obs]", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="prop[obs]", 
                        `title`="Proportion", 
                        `type`="number"),
                    list(
                        `name`="name[exp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Expected", 
                        `visible`="(expected)"),
                    list(
                        `name`="count[exp]", 
                        `title`="Count", 
                        `type`="number", 
                        `visible`="(expected)"),
                    list(
                        `name`="prop[exp]", 
                        `title`="Proportion", 
                        `type`="number", 
                        `visible`="(expected)"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tests",
                title="Proportions analysis",
                rows=3,
                clearWith=list(
                    "var",
                    "ratio",
                    "counts"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Hypotheses", 
                        `type`="text"),
                    list(
                        `name`="Values", 
                        `title`="Expected values", 
                        `type`="text"),
                    list(
                        `name`="S", 
                        `type`="number"),
                    list(
                        `name`="Sc", 
                        `type`="number"),
                    list(
                        `name`="G", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "Edwards_OR")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt2",
                title="Intervals for Proportion",
                visible=FALSE,
                rows=2,
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="P", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `refs`=list(
                            "Aitkin")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt3",
                title="Variance analyses",
                visible=FALSE,
                rows=2,
                clearWith=list(
                    "cc"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Hypotheses", 
                        `type`="text"),
                    list(
                        `name`="Sv", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="X2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="dfv", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="pv", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pv1", 
                        `title`="1 - p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "EdwardsVA")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood function for Proportion with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                visible=FALSE))}))

propBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "propBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Likelihood",
                name = "prop",
                version = c(1,0,0),
                options = options,
                results = propResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' LR One-Way Analysis
#'
#' The one-way analysis examines how well the observed proportions match those 
#' expected according to a null hypothesis or a specified hypothesis. 
#' 
#' @param data the data as a data frame
#' @param var .
#' @param counts the counts in \code{data}
#' @param expected \code{TRUE} or \code{FALSE} (default), whether expected
#'   counts should be displayed
#' @param bi .
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param lint .
#' @param pll .
#' @param ratio a vector of numbers: the expected proportions
#' @param varA .
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$props} \tab \tab \tab \tab \tab a table of the proportions \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tests} \tab \tab \tab \tab \tab a table of the test results \cr
#'   \code{results$ctt2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ctt3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$props$asDF}
#'
#' \code{as.data.frame(results$props)}
#'
#' @export
prop <- function(
    data,
    var,
    counts = NULL,
    expected = FALSE,
    bi = FALSE,
    ciWidth = 95,
    lint = 2,
    pll = FALSE,
    ratio = NULL,
    varA = FALSE,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("prop requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(counts))
            counts <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                subset="1")
        if (missing(var))
            var <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                subset="1")
    }

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- propOptions$new(
        var = var,
        counts = counts,
        expected = expected,
        bi = bi,
        ciWidth = ciWidth,
        lint = lint,
        pll = pll,
        ratio = ratio,
        varA = varA)

    analysis <- propClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

